apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db-deployment
spec:
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - image: mysql:5.7
        name: mysql-container
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-db-secret
              key: pword
        ports:
        - containerPort: 3306
          name: mysql-db
        volumeMounts:
        - name: mysql-db-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-db-volume
        persistentVolumeClaim:
          claimName: mysql-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db-svc
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-db
